"""Run the main PoC 1 BIM quality pipeline in a fixed order."""

from __future__ import annotations

import subprocess
import sys
import time
from dataclasses import dataclass
from pathlib import Path


BASE_DIR = Path(__file__).resolve().parents[1]


@dataclass(frozen=True)
class PipelineStep:
    name: str
    script: Path
    expected_outputs: tuple[Path, ...]


PIPELINE_STEPS = (
    PipelineStep(
        name="BIM quality check",
        script=BASE_DIR / "src" / "check_bim_quality.py",
        expected_outputs=(
            BASE_DIR / "04_output_csv" / "check_results_revit_v002.csv",
        ),
    ),
    PipelineStep(
        name="Quality metrics calculation",
        script=BASE_DIR / "src" / "calculate_quality_metrics.py",
        expected_outputs=(
            BASE_DIR / "04_output_csv" / "quality_metrics_v001.csv",
            BASE_DIR / "04_output_csv" / "rule_summary_v001.csv",
            BASE_DIR / "04_output_csv" / "category_summary_v001.csv",
            BASE_DIR / "04_output_csv" / "element_summary_v001.csv",
        ),
    ),
    PipelineStep(
        name="BIM feature creation",
        script=BASE_DIR / "src" / "create_bim_features.py",
        expected_outputs=(
            BASE_DIR / "04_output_csv" / "bim_features_v001.csv",
        ),
    ),
    PipelineStep(
        name="FixPriority model workflow",
        script=BASE_DIR / "src" / "train_fix_priority_model.py",
        expected_outputs=(
            BASE_DIR / "04_output_csv" / "fix_priority_classification_report_v001.csv",
            BASE_DIR / "04_output_csv" / "fix_priority_confusion_matrix_v001.csv",
            BASE_DIR / "04_output_csv" / "fix_priority_predictions_v001.csv",
        ),
    ),
    PipelineStep(
        name="AI readiness assessment",
        script=BASE_DIR / "src" / "calculate_ai_readiness_score.py",
        expected_outputs=(
            BASE_DIR / "04_output_csv" / "ai_readiness_scores_v001.csv",
        ),
    ),
    PipelineStep(
        name="AI context generation",
        script=BASE_DIR / "src" / "generate_ai_context.py",
        expected_outputs=(
            BASE_DIR / "04_output_csv" / "ai_context_v002.json",
            BASE_DIR / "04_output_csv" / "ai_context_v002.md",
        ),
    ),
    PipelineStep(
        name="Fix guide generation",
        script=BASE_DIR / "src" / "generate_fix_guide.py",
        expected_outputs=(
            BASE_DIR / "04_output_csv" / "fix_guides_v001.md",
        ),
    ),
)


def display_path(path: Path) -> str:
    try:
        return path.relative_to(BASE_DIR).as_posix()
    except ValueError:
        return str(path)


def validate_pipeline_definition() -> None:
    missing_scripts = [
        step.script for step in PIPELINE_STEPS if not step.script.is_file()
    ]

    if missing_scripts:
        missing_text = "\n".join(
            f"- {display_path(path)}" for path in missing_scripts
        )
        raise FileNotFoundError(
            f"Pipeline scripts are missing:\n{missing_text}"
        )


def run_step(step_number: int, step: PipelineStep) -> float:
    total_steps = len(PIPELINE_STEPS)

    print()
    print("=" * 72)
    print(f"[{step_number}/{total_steps}] {step.name}")
    print(f"Script: {display_path(step.script)}")
    print("=" * 72)

    started_at = time.perf_counter()

    completed = subprocess.run(
        [sys.executable, str(step.script)],
        cwd=BASE_DIR,
        check=False,
    )

    elapsed = time.perf_counter() - started_at

    if completed.returncode != 0:
        raise RuntimeError(
            f"Pipeline step failed: {step.name} "
            f"(exit code: {completed.returncode})"
        )

    missing_outputs = [
        path for path in step.expected_outputs if not path.is_file()
    ]

    if missing_outputs:
        missing_text = "\n".join(
            f"- {display_path(path)}" for path in missing_outputs
        )
        raise FileNotFoundError(
            f"Expected outputs were not generated by {step.name}:\n"
            f"{missing_text}"
        )

    empty_outputs = [
        path
        for path in step.expected_outputs
        if path.stat().st_size == 0
    ]

    if empty_outputs:
        empty_text = "\n".join(
            f"- {display_path(path)}" for path in empty_outputs
        )
        raise RuntimeError(
            f"Empty output files were generated by {step.name}:\n"
            f"{empty_text}"
        )

    print(f"Step completed in {elapsed:.2f} seconds.")

    for output in step.expected_outputs:
        print(
            f"Verified: {display_path(output)} "
            f"({output.stat().st_size} bytes)"
        )

    return elapsed


def main() -> int:
    print("PoC 1 main pipeline started.")
    print(f"Python: {sys.version.split()[0]}")
    print(f"Executable: {sys.executable}")
    print(f"Repository: {BASE_DIR}")

    try:
        validate_pipeline_definition()

        total_started_at = time.perf_counter()
        step_durations: list[tuple[str, float]] = []

        for step_number, step in enumerate(PIPELINE_STEPS, start=1):
            elapsed = run_step(step_number, step)
            step_durations.append((step.name, elapsed))

        total_elapsed = time.perf_counter() - total_started_at

    except Exception as exc:
        print()
        print("PIPELINE FAILED")
        print(f"{type(exc).__name__}: {exc}")
        return 1

    print()
    print("=" * 72)
    print("PIPELINE COMPLETED")
    print("=" * 72)

    for name, elapsed in step_durations:
        print(f"- {name}: {elapsed:.2f} seconds")

    print(f"Total steps: {len(PIPELINE_STEPS)}")
    print(f"Total time: {total_elapsed:.2f} seconds")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
